import { historicalLintIgnorePaths, loadQualityGatePolicy } from "./audit/lib/quality-gate-policy.mjs";

const historicalIgnores = historicalLintIgnorePaths(await loadQualityGatePolicy());
const metricWarnings = Object.freeze({
  complexity: ["warn", { max: 10, variant: "classic" }],
  "max-depth": ["warn", 4],
  "max-lines-per-function": ["warn", {
    max: 80,
    skipBlankLines: true,
    skipComments: true,
    IIFEs: true,
  }],
  "max-params": ["warn", 5],
  "max-statements": ["warn", 40],
  "no-promise-executor-return": "warn",
  "no-unsafe-finally": "warn",
  "no-useless-escape": "warn",
});

export default [
  {
    ignores: [
      ...historicalIgnores,
      "**/node_modules/**",
      "**/.artifacts/**",
      "**/.tmp*/**",
      "audit-artifacts/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },
  {
    files: ["**/*.js", "**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-constant-binary-expression": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-ex-assign": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-undef-init": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": ["warn", {
        args: "after-used",
        argsIgnorePattern: "^_",
        caughtErrors: "none",
        ignoreRestSiblings: true,
        varsIgnorePattern: "^_",
      }],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      ...metricWarnings,
    },
  },
];
